#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>


int parseur(char *c, int l, char *s, void (*callback)());
int est_absolute_form(char *c, int l, char *s, int ls, void (*callback)());
int est_absolute_path(char *c, int l, char *s, int ls, void (*callback)());
int est_absolute_uri(char *c, int l, char *s, int ls, void (*callback)());
int est_accept(char *c, int l, char *s, int ls, void (*callback)());
int est_acceptable_ranges(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_charset(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_charset_header(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_encoding(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_encoding_header(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_ext(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_header(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_language(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_language_header(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_params(char *c, int l, char *s, int ls, void (*callback)());
int est_accept_ranges(char *c, int l, char *s, int ls, void (*callback)());
int est_age(char *c, int l, char *s, int ls, void (*callback)());
int est_age_header(char *c, int l, char *s, int ls, void (*callback)());
int est_allow(char *c, int l, char *s, int ls, void (*callback)());
int est_alpha(char c);
int est_alphanum(char c);
int est_asctime_date(char *c, int l, char *s, int ls, void (*callback)());
int est_asterisk_form(char c);
int est_authority(char *c, int l, char *s, int ls, void (*callback)());
int est_authority_form(char *c, int l, char *s, int ls, void (*callback)());
int est_authorization(char *c, int l, char *s, int ls, void (*callback)());
int est_authorization_header(char *c, int l, char *s, int ls, void (*callback)());
int est_auth_param(char *c, int l, char *s, int ls, void (*callback)());
int est_auth_scheme(char *c, int l, char *s, int ls, void (*callback)());
int est_byte_content_range(char *c, int l, char *s, int ls, void (*callback)());
int est_byte_range(char *c, int l, char *s, int ls, void (*callback)());
int est_byte_range_resp(char *c, int l, char *s, int ls, void (*callback)());
int est_byte_range_set(char *c, int l, char *s, int ls, void (*callback)());
int est_byte_range_spec(char *c, int l, char *s, int ls, void (*callback)());
int est_byte_ranges_specifier(char *c, int l,  char *s, int ls, void (*callback)());
int est_bytes_unit(char *c, int l, char *s, int ls, void (*callback)());
int est_cache_control(char *c, int l, char *s, int ls, void (*callback)());
int est_cache_control_header(char *c, int l, char *s, int ls, void (*callback)());
int est_cache_directive(char *c, int l, char *s, int ls, void (*callback)());
int est_challenge(char *c, int l, char *s, int ls, void (*callback)());
int est_char(char c);
int est_charset(char *c, int l, char *s, int ls, void (*callback)());
int est_chunk(char *c, int l, char *s, int ls, void (*callback)());
int est_chunk_data(char *c, int l, char *s, int ls, void (*callback)());
int est_chunked_body(char *c, int l, char *s, int ls, void (*callback)());
int est_chunk_ext(char *c, int l, char *s, int ls, void (*callback)());
int est_chunk_ext_name(char *c, int l, char *s, int ls, void (*callback)());
int est_chunk_ext_val(char *c, int l, char *s, int ls, void (*callback)());
int est_chunk_size(char *c, int l, char *s, int ls, void (*callback)());
int est_codings(char *c, int l, char *s, int ls, void (*callback)());
int est_comment(char *c, int l, char *s, int ls, void (*callback)());
int est_complete_length(char *c, int l, char *s, int ls, void (*callback)());
int est_connection(char *c, int l, char *s, int ls, void (*callback)());
int est_connection_header(char *c, int l, char *s, int ls, void (*callback)());
int est_connection_option(char *c, int l, char *s, int ls, void (*callback)());
int est_content_coding(char *c, int l, char *s, int ls, void (*callback)());
int est_content_encoding(char *c, int l, char *s, int ls, void (*callback)());
int est_content_language(char *c, int l, char *s, int ls, void (*callback)());
int est_content_length(char *c, int l, char *s, int ls, void (*callback)());
int est_content_length_header(char *c, int l, char *s, int ls, void (*callback)());
int est_content_location(char *c, int l, char *s, int ls, void (*callback)());
int est_content_range(char *c, int l, char *s, int ls, void (*callback)());
int est_content_type(char *c, int l, char *s, int ls, void (*callback)());
int est_cookie_header(char *c, int l, char *s, int ls, void (*callback)());
int est_cookie_name(char *c, int l, char *s, int ls, void (*callback)());
int est_cookie_octet(char c);
int est_cookie_pair(char *c, int l, char *s, int ls, void (*callback)());
int est_cookie_string(char *c, int l, char *s, int ls, void (*callback)());
int est_cookie_value(char *c, int l, char *s, int ls, void (*callback)());
int est_credentials(char *c, int l, char *s, int ls, void (*callback)());
int est_crlf(char *c, int l, char *s, int ls, void (*callback)());
int est_ctext(char c);
int est_date(char *c, int l, char *s, int ls, void (*callback)());
int est_date1(char *c, int l, char *s, int ls, void (*callback)());
int est_date2(char *c, int l, char *s, int ls, void (*callback)());
int est_date3(char *c, int l, char *s, int ls, void (*callback)());
int est_date_header(char *c, int l, char *s, int ls, void (*callback)());
int est_day(char *c, int l, char *s, int ls, void (*callback)());
int est_day_name(char *c, int l, char *s, int ls, void (*callback)());
int est_day_name_l(char *c, int l, char *s, int ls, void (*callback)());
int est_dec_octet(char *c, int l, char *s, int ls, void (*callback)());
int est_delay_seconds(char *c, int l, char *s, int ls, void (*callback)());
int est_delta_seconds(char *c, int l, char *s, int ls, void (*callback)());
int est_digit(char c);
int est_dquote(char c);
int est_entity_tag(char *c, int l, char *s, int ls, void (*callback)());
int est_etag(char *c, int l, char *s, int ls, void (*callback)());
int est_etagc(char c);
int est_expect(char *c, int l, char *s, int ls, void (*callback)());
int est_expect_header(char *c, int l, char *s, int ls, void (*callback)());
int est_expires(char *c, int l, char *s, int ls, void (*callback)());
int est_expires_header(char *c, int l, char *s, int ls, void (*callback)());
int est_extension(char *c, int l, char *s, int ls, void (*callback)());
int est_extension_pragma(char *c, int l, char *s, int ls, void (*callback)());
int est_extlang(char *c, int l, char *s, int ls, void (*callback)());
int est_field_content(char *c, int l, char *s, int ls, void(*callback)());
int est_field_name(char *c, int l, char *s, int ls, void (*callback)());
int est_field_value(char *c, int l, char *s, int ls, void (*callback)());
int est_field_vchar(char *c, int l, char *s, int ls, void (*callback)());
int est_first_byte_pos(char *c, int l, char *s, int ls, void (*callback)());
int est_fragment(char *c, int l, char *s, int ls, void (*callback)());
int est_gen_delims(char c);
int est_gmt(char *c, int l, char *s, int ls, void (*callback)());
int est_grandfathered(char *c, int l, char *s, int ls, void(*callback)());
int est_h16(char *c, int l, char *s, int ls, void (*callback)());
int est_header_field(char *c, int l, char *s, int ls, void (*callback)());
int est_hexdig(char c);
int est_hier_part(char *c, int l, char *s, int ls, void (*callback)());
int est_host(char *c, int l, char *s, int ls, void (*callback)());
int est_host2(char *c, int l, char *s, int ls, void(*callback)());
int est_host_header(char *c, int l, char *s, int ls, void (*callback)());
int est_hour(char *c, int l, char *s, int ls, void (*callback)());
int est_htab(char c);
int est_http_date(char *c, int l, char *s, int ls, void (*callback)());
int est_http_message(char *c, int l, char *s, int ls, void (*callback)());
int est_http_name(char *c, int l, char *s, int ls, void (*callback)());
int est_https_uri(char *c, int l, char *s, int ls, void (*callback)());
int est_http_uri(char *c, int l, char *s, int ls, void (*callback)());
int est_http_version(char *c, int l, char *s, int ls, void (*callback)());
int est_if_match(char *c, int l, char *s, int ls, void (*callback)());
int est_if_match_header(char *c, int l, char *s, int ls, void (*callback)());
int est_if_modified_since(char *c, int l, char *s, int ls, void (*callback)());
int est_if_modified_since_header(char *c, int l, char *s, int ls, void (*callback)());
int est_if_none_match(char *c, int l, char *s, int ls, void (*callback)());
int est_if_none_match_header(char *c, int l, char *s, int ls, void (*callback)());
int est_if_range(char *c, int l, char *s, int ls, void (*callback)());
int est_if_range_header(char *c, int l, char *s, int ls, void (*callback)());
int est_if_unmodified_since(char *c, int l, char *s, int ls, void (*callback)());
int est_if_unmodified_since_header(char *c, int l, char *s, int ls, void (*callback)());
int est_imf_fixdate(char *c, int l, char *s, int ls, void (*callback)());
int est_ip_literal(char *c, int l, char *s, int ls, void (*callback)());
int est_ipv4address(char *c, int l, char *s, int ls, void (*callback)());
int est_ipv6address(char *c, int l, char *s, int ls, void (*callback)());
int est_ipvfuture(char *c, int l, char *s, int ls, void (*callback)());
int est_irregular(char *c, int l, char *s, int ls, void (*callback)());
int est_langtag(char *c, int l, char *s, int ls, void (*callback)());
int est_language(char *c, int l, char *s, int ls, void (*callback)());
int est_language_range(char *c, int l, char *s, int ls, void (*callback)());
int est_language_tag(char *c, int l, char *s, int ls, void (*callback)());
int est_last_byte_pos(char *c, int l, char *s, int ls, void (*callback)());
int est_last_chunk(char *c, int l, char *s, int ls, void (*callback)());
int est_last_modified(char *c, int l, char *s, int ls, void (*callback)());
int est_location(char *c, int l, char *s, int ls, void (*callback)());
int est_location_header(char *c, int l, char *s, int ls, void (*callback)());
int est_ls32(char *c, int l, char *s, int ls, void (*callback)());
int est_max_forwards(char *c, int l, char *s, int ls, void (*callback)());
int est_max_forwards_header(char *c, int l, char *s, int ls, void (*callback)());
int est_media_range(char *c, int l, char *s, int ls, void (*callback)());
int est_media_type(char *c, int l, char *s, int ls, void (*callback)());
int est_message_body(char *c, int l, char *s, int ls, void (*callback)());
int est_method(char *c, int l, char *s, int ls, void(*callback)());
int est_minute(char *c, int l, char *s, int ls, void (*callback)());
int est_month(char *c, int l, char *s, int ls, void (*callback)());
int est_obs_date(char *c, int l, char *s, int ls, void (*callback)());
int est_obs_fold(char *c, int l, char *s, int ls, void (*callback)());
int est_obs_text(char c);
int est_opaque_tag(char *c, int l, char *s, int ls, void (*callback)());
int est_origin_form(char *c, int l, char *s, int ls, void (*callback)());
int est_other_content_range(char *c, int l, char *s, int ls, void (*callback)());
int est_other_range_resp(char *c, int l, char *s, int ls, void (*callback)());
int est_other_range_set(char *c, int l, char *s, int ls, void (*callback)());
int est_other_ranges_specifier(char *c, int l, char *s, int ls, void (*callback)());
int est_other_range_unit(char *c, int l, char *s, int ls, void (*callback)());
int est_parameter(char *c, int l, char *s, int ls, void (*callback)());
int est_partial_uri(char *c, int l, char *s, int ls, void (*callback)());
int est_path(char *c, int l, char *s, int ls, void (*callback)());
int est_path_abempty(char *c, int l, char *s, int ls, void (*callback)());
int est_path_absolute(char *c, int l, char *s, int ls, void (*callback)());
int est_path_empty(char *c, int l, char *s, int ls, void (*callback)());
int est_path_noscheme(char *c, int l, char *s, int ls, void (*callback)());
int est_path_rootless(char *c, int l, char *s, int ls, void (*callback)());
int est_pchar(char *c, int l, char *s, int ls, void (*callback)());
int est_pct_encoded(char *c, int l, char *s,int ls, void (*callback)());
int est_port(char *c, int l, char *s, int ls, void (*callback)());
int est_pragma(char *c, int l, char *s, int ls, void (*callback)());
int est_pragma_directive(char *c, int l, char *s, int ls, void (*callback)());
int est_pragma_header(char *c, int l, char *s, int ls, void (*callback)());
int est_privateuse(char *c, int l, char *s, int ls, void (*callback)());
int est_product(char *c, int l, char *s, int ls, void (*callback)());
int est_product_version(char *c, int l, char *s, int ls, void (*callback)());
int est_protocol(char *c, int l, char *s, int ls, void (*callback)());
int est_protocol_name(char *c, int l, char *s, int ls, void (*callback)());
int est_protocol_version(char *c, int l, char *s, int ls, void (*callback)());
int est_proxy_authenticate(char *c, int l, char *s, int ls, void (*callback)());
int est_proxy_authorization(char *c, int l, char *s, int ls, void (*callback)());
int est_proxy_authorization_header(char *c, int l, char *s, int ls, void (*callback)());
int est_pseudonym(char *c, int l, char *s, int ls, void (*callback)());
int est_qdtext(char c);
int est_query(char *c, int l, char *s, int ls, void (*callback)());
int est_quoted_pair(char *c, int l, char *s, int ls, void (*callback)());
int est_quoted_string(char *c, int l, char *s, int ls, void (*callback)());
int est_qvalue(char *c, int l, char *s, int ls, void (*callback)());
int est_range(char *c, int l, char *s, int ls, void (*callback)());
int est_range_header(char *c, int l, char *s, int ls, void (*callback)());
int est_range_unit(char *c, int l, char *s, int ls, void (*callback)());
int est_rank(char *c, int l, char *s, int ls, void (*callback)());
int est_reason_phrase(char *c, int l, char *s, int ls, void (*callback)());
int est_received_by(char *c, int l, char *s, int ls, void (*callback)());
int est_received_protocol(char *c, int l, char *s, int ls, void (*callback)());
int est_referer(char *c, int l, char *s, int ls, void (*callback)());
int est_referer_header(char *c, int l, char *s, int ls, void (*callback)());
int est_region(char *c, int l, char *s, int ls, void (*callback)());
int est_reg_name(char *c, int l, char *s, int ls, void (*callback)());
int est_regular(char *c, int l, char *s, int ls, void (*callback)());
int est_relative_part(char *c, int l, char *s, int ls, void (*callback)());
int est_relative_ref(char *c, int l, char *s, int ls, void (*callback)());
int est_request_line(char *c, int l, char *s, int ls, void (*callback)());
int est_request_target(char *c, int l, char *s, int ls, void (*callback)());
int est_reserved(char c);
int est_request_target(char *c, int l, char *s, int ls, void (*callback)());
int est_reserved(char c);
int est_retry_after(char *c, int l, char *s, int ls, void (*callback)());
int est_retry_after_header(char *c, int l, char *s, int ls, void (*callback)());
int est_rfc850_date(char *c, int l, char *s, int ls, void (*callback)());
int est_scheme(char *c, int l, char *s, int ls, void (*callback)());
int est_script(char *c, int l, char *s, int ls, void (*callback)());
int est_second(char *c, int l, char *s, int ls, void (*callback)());
int est_segment(char *c, int l, char *s,int ls, void (*callback)());
int est_segment_nz(char *c, int l, char *s, int ls, void (*callback)());
int est_segment_nz_nc(char *c, int l, char *s, int ls, void (*callback)());
int est_server(char *c, int l, char *s, int ls, void (*callback)());
int est_singleton(char c);
int est_sp(char c);
int est_start_line(char *c, int l, char *s, int ls, void (*callback)());
int est_status_code(char *c, int l, char *s, int ls, void (*callback)());
int est_status_line(char *c, int l, char *s, int ls, void (*callback)());
int est_sub_delims(char c);
int est_subtype(char *c, int l, char *s, int ls, void (*callback)());
int est_suffix_byte_range_spec(char *c, int l, char *s, int ls, void (*callback)());
int est_suffix_length(char *c, int l, char *s, int ls, void (*callback)());
int est_tchar(char c);
int est_t_codings(char *c, int l, char *s, int ls, void (*callback)());
int est_te(char *c, int l, char *s, int ls, void (*callback)());
int est_te_header(char *c, int l, char *s, int ls, void (*callback)());
int est_time_of_day(char *c, int l, char *s, int ls, void (*callback)());
int est_token(char *c, int l, char *s, int ls, void (*callback)());
int est_token68 (char*c, int l, char *s, int ls, void (*callback)());
int est_trailer(char *c, int l, char *s, int ls, void (*callback)());
int est_trailer_header(char *c, int l, char *s, int ls, void (*callback)());
int est_trailer_part(char *c, int l, char *s, int ls, void (*callback)());
int est_t_ranking(char *c, int l, char *s, int ls, void (*callback)());
int est_transfer_coding(char *c, int l, char *s, int ls, void (*callback)());
int est_transfer_encoding(char *c, int l, char *s, int ls, void (*callback)());
int est_transfer_encoding_header(char *c, int l, char *s, int ls, void (*callback)());
int est_transfer_extension(char *c, int l, char *s, int ls, void (*callback)());
int est_transfer_parameter(char *c, int l, char *s, int ls, void (*callback)());
int est_type(char *c, int l, char *s, int ls, void (*callback)());
int est_unreserved(char c);
int est_unsatisfied_range(char *c, int l, char *s, int ls, void (*callback)());
int est_upgrade(char *c, int l, char *s, int ls, void (*callback)());
int est_upgrade_header(char *c, int l, char *s, int ls, void (*callback)());
int est_uri(char *c, int l, char *s, int ls, void (*callback)());
int est_uri_host(char *c, int l, char *s, int ls, void (*callback)());
int est_uri_reference(char *c, int l, char *s, int ls, void (*callback)());
int est_user_agent(char *c, int l, char *s, int ls, void (*callback)());
int est_user_agent_header(char *c, int l, char *s, int ls, void (*callback)());
int est_userinfo(char *c, int l, char *s, int ls, void (*callback)());
int est_variant(char *c, int l, char *s, int ls, void (*callback)());
int est_vary(char *c, int l, char *s, int ls, void (*callback)());
int est_vary_header(char *c, int l, char *s, int ls, void (*callback)());
int est_vchar(char c);
int est_via(char *c, int l, char *s, int ls, void (*callback)());
int est_via_header(char *c, int l, char *s, int ls, void (*callback)());
int est_warn_agent(char *c, int l, char *s, int ls, void (*callback)());
int est_warn_code(char *c, int l, char *s, int ls, void (*callback)());
int est_warn_date(char *c, int l, char *s, int ls, void (*callback)());
int est_warning(char *c, int l, char *s, int ls, void (*callback)());
int est_warning_header(char *c, int l, char *s, int ls, void (*callback)());
int est_warn_text(char *c, int l, char *s, int ls, void (*callback)());
int est_warning_value(char *c, int l, char *s, int ls, void (*callback)());
int est_weak(char *c, int l, char *s, int ls, void (*callback)());
int est_weight(char *c, int l, char *s, int ls, void (*callback)());
int est_www_authenticate(char *c, int l, char *s, int ls, void (*callback)());
int est_year(char *c, int l, char *s, int ls, void (*callback)());
